version: '3.7'
services:
  web:
    build: ./web
    # image: mikeryan56/pynote:0.1.4
    image: mikeryan56/pynote:latest
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    environment:
      VIRTUAL_HOST: pynote.devsetgo.com
      LETSENCRYPT_HOST: pynote.devsetgo.com
    deploy:
#      replicas: 2
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
      restart_policy:
        condition: always