# FROM ubuntu:latest
# MAINTAINER Mike Ryan "mikeryan56@gmail.com"
# RUN apt-get update -y
# RUN apt-get install -y python-pip python-dev build-essential
# COPY . /app
# WORKDIR /app
# RUN pip install -r requirements.txt
# ENTRYPOINT ["python"]
# CMD ["wsgi.py"]

FROM python:3.6-alpine
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
#EXPOSE 5000/udp
ENV VIRTUAL_HOST pynote.devsetgo.com
ENV LETSENCRYPT_HOST pynote.devsetgo.com
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["wsgi.py"]
